import os
import subprocess
import psutil

class ServerManager:
    def __init__(self, config_manager):
        self.config_manager = config_manager
        self.server_process = None

    def get_server_directory(self):
        # Retrieve the server path, default to a 'server' directory in the config folder
        path = self.config_manager.get("local_server_path")
        if not path:
            path = os.path.join(self.config_manager.get_minecraft_folder(), "server")
            self.config_manager.set("local_server_path", path)
        if not os.path.exists(path):
            try:
                os.makedirs(path, exist_ok=True)
            except Exception as e:
                print(f"Error creating server directory: {e}")
        return path

    def set_server_directory(self, path):
        if path and os.path.exists(path):
            self.config_manager.set("local_server_path", path)
            return True
        return False

    def find_server_jar(self):
        directory = self.get_server_directory()
        if not os.path.exists(directory):
            return None
        
        files = os.listdir(directory)
        jar_files = [f for f in files if f.endswith(".jar")]
        
        if not jar_files:
            return None
        
        # Order of preference for server jars
        prefer_keywords = ["paper", "purpur", "spigot", "forge", "fabric", "server"]
        for kw in prefer_keywords:
            for jar in jar_files:
                if kw in jar.lower():
                    return os.path.join(directory, jar)
        
        # Fallback to the first jar file
        return os.path.join(directory, jar_files[0])

    def open_server_properties(self):
        directory = self.get_server_directory()
        properties_path = os.path.join(directory, "server.properties")
        
        # If it doesn't exist, create an empty or minimal one
        if not os.path.exists(properties_path):
            try:
                with open(properties_path, "w") as f:
                    f.write("# Minecraft Server Properties\n")
                    f.write("# Generated by Alien Launcher\n")
                    f.write("server-port=25565\n")
                    f.write("online-mode=false\n") # Good for private Tailscale testing
                    f.write("motd=Alien Private Server\n")
            except Exception as e:
                return False, f"Could not create server.properties: {e}"
        
        try:
            os.startfile(properties_path)
            return True, "Opened server.properties successfully."
        except Exception as e:
            return False, f"Error opening file: {e}"

    def start_server(self, java_path=None, ram_min="1G", ram_max="2G"):
        if self.is_running():
            return False, "Server is already running."

        server_jar = self.find_server_jar()
        if not server_jar:
            return False, "No server .jar file found in the server directory.\nPlease place your server jar (e.g. server.jar) in the server folder."

        if not java_path:
            java_path = self.config_manager.get("java_path") or "java"

        # Construct the execution command
        # e.g., java -Xms1G -Xmx2G -jar server.jar nogui
        cmd = [
            java_path,
            f"-Xms{ram_min}",
            f"-Xmx{ram_max}",
            "-jar",
            os.path.basename(server_jar),
            "nogui"
        ]

        # We need to run the server in its directory so it finds files locally
        working_dir = self.get_server_directory()

        # Update online-mode in server.properties and inject authlib-injector for Ely.by
        account_type = self.config_manager.get("account_type", "Offline")
        if account_type == "Ely.by":
            import sys
            if getattr(sys, 'frozen', False):
                injector_path = os.path.join(os.path.dirname(sys.executable), "assets", "authlib-injector.jar")
            else:
                injector_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "assets", "authlib-injector.jar")
            if os.path.exists(injector_path):
                cmd.insert(1, f"-javaagent:{injector_path}=ely.by")
            self.ensure_server_online_mode(working_dir, True)
        elif account_type == "Microsoft":
            self.ensure_server_online_mode(working_dir, True)
        else:
            self.ensure_server_online_mode(working_dir, False)

        # Agree to EULA if not present, to save user frustration
        eula_path = os.path.join(working_dir, "eula.txt")
        if not os.path.exists(eula_path):
            try:
                with open(eula_path, "w") as f:
                    f.write("eula=true\n")
            except Exception as e:
                print(f"Could not automatically agree to EULA: {e}")

        try:
            # Hide the cmd window on Windows
            startupinfo = subprocess.STARTUPINFO()
            startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
            startupinfo.wShowWindow = 0 # SW_HIDE

            self.server_process = subprocess.Popen(
                cmd,
                cwd=working_dir,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                stdin=subprocess.PIPE,
                text=True,
                startupinfo=startupinfo
            )
            return True, "Server started successfully."
        except Exception as e:
            return False, f"Failed to start server: {e}"

    def ensure_server_online_mode(self, working_dir, online_mode):
        properties_path = os.path.join(working_dir, "server.properties")
        if not os.path.exists(properties_path):
            return
        
        try:
            with open(properties_path, "r") as f:
                lines = f.readlines()
            
            target_value = "true" if online_mode else "false"
            modified = False
            for i, line in enumerate(lines):
                if line.strip().startswith("online-mode="):
                    current_value = line.split("=")[1].strip()
                    if current_value != target_value:
                        lines[i] = f"online-mode={target_value}\n"
                        modified = True
                    break
            else:
                lines.append(f"online-mode={target_value}\n")
                modified = True
                
            if modified:
                with open(properties_path, "w") as f:
                    f.writelines(lines)
        except Exception as e:
            print(f"Error updating online-mode in server.properties: {e}")

    def stop_server(self):
        if not self.is_running():
            return False, "Server is not running."
        
        try:
            # 1. Graceful stop if we have the process handle
            if self.server_process and self.server_process.stdin:
                try:
                    self.server_process.stdin.write("stop\n")
                    self.server_process.stdin.flush()
                    self.server_process.wait(timeout=10)
                    self.server_process = None
                    return True, "Server stopped gracefully."
                except Exception:
                    pass
            
            # 2. Terminate matching background processes
            import psutil
            server_dir = os.path.abspath(self.get_server_directory())
            terminated_any = False
            for proc in psutil.process_iter(['name']):
                try:
                    name = proc.info.get('name')
                    if name and 'java' in name.lower():
                        proc_cwd = proc.cwd()
                        if proc_cwd and os.path.abspath(proc_cwd) == server_dir:
                            proc.terminate()
                            proc.wait(timeout=5)
                            terminated_any = True
                except Exception:
                    pass
                    
            if terminated_any:
                self.server_process = None
                return True, "Background server process stopped."
            
            # 3. Fallback kill handle
            if self.server_process:
                self.server_process.terminate()
                self.server_process.wait(timeout=5)
                self.server_process = None
                return True, "Server process terminated."
        except Exception as e:
            if self.server_process:
                try:
                    self.server_process.kill()
                except Exception:
                    pass
            self.server_process = None
            return False, f"Error terminating server: {e}"

    def is_running(self):
        # 1. Check handle first
        if self.server_process is not None:
            poll = self.server_process.poll()
            if poll is None:
                return True
            self.server_process = None
            
        # 2. Check running processes on the system
        try:
            import psutil
            server_dir = os.path.abspath(self.get_server_directory())
            for proc in psutil.process_iter(['name']):
                try:
                    name = proc.info.get('name')
                    if name and 'java' in name.lower():
                        proc_cwd = proc.cwd()
                        if proc_cwd and os.path.abspath(proc_cwd) == server_dir:
                            return True
                except (psutil.NoSuchProcess, psutil.AccessDenied, psutil.ZombieProcess):
                    pass
        except Exception:
            pass
            
        return False

    def get_server_log_tail(self, num_lines=20):
        working_dir = self.get_server_directory()
        log_path = os.path.join(working_dir, "logs", "latest.log")
        if not os.path.exists(log_path):
            if self.is_running():
                return "[System] Server is booting up, logs will appear shortly...\n"
            return "[System] No server log file found yet. Click 'Start Server' to launch.\n"
        try:
            with open(log_path, "r", encoding="utf-8", errors="ignore") as f:
                lines = f.readlines()
                return "".join(lines[-num_lines:])
        except Exception as e:
            return f"Error reading log: {e}"

    def update_server_properties(self, properties_path, updates):
        lines = []
        existing = {}
        if os.path.exists(properties_path):
            try:
                with open(properties_path, "r", encoding="utf-8", errors="ignore") as f:
                    lines = f.readlines()
            except Exception:
                pass
                
        for line in lines:
            if "=" in line and not line.strip().startswith("#"):
                k, v = line.split("=", 1)
                existing[k.strip()] = v.strip()
                
        for k, v in updates.items():
            existing[k] = v
            
        try:
            with open(properties_path, "w", encoding="utf-8") as f:
                f.write("# Minecraft Server Properties\n")
                f.write("# Updated by Alien Launcher\n")
                for k, v in existing.items():
                    f.write(f"{k}={v}\n")
        except Exception as e:
            print(f"Error updating server.properties: {e}")

    def download_fabric_api(self, minecraft_version, mods_dir, status_cb):
        import requests

        status_cb("Downloading Fabric API for Fabric server dependencies...")
        headers = {"User-Agent": "Alien-Launcher/1.0.0"}
        
        # 1. Try exact game version
        versions = []
        try:
            params = {
                "game_versions": f'["{minecraft_version}"]',
                "loaders": '["fabric"]'
            }
            res = requests.get(
                "https://api.modrinth.com/v2/project/fabric-api/version",
                params=params,
                headers=headers,
                timeout=15
            )
            if res.status_code == 200:
                versions = res.json()
        except Exception as e:
            print(f"Error querying exact Fabric API version: {e}")

        # 2. Try major/minor version match (e.g. 1.20 instead of 1.20.1)
        if not versions and "." in minecraft_version:
            try:
                major_version = ".".join(minecraft_version.split(".")[:2])
                params = {
                    "game_versions": f'["{major_version}"]',
                    "loaders": '["fabric"]'
                }
                res = requests.get(
                    "https://api.modrinth.com/v2/project/fabric-api/version",
                    params=params,
                    headers=headers,
                    timeout=15
                )
                if res.status_code == 200:
                    versions = res.json()
            except Exception as e:
                print(f"Error querying major Fabric API version: {e}")

        # 3. Try fetching any available versions
        if not versions:
            try:
                params = {
                    "loaders": '["fabric"]'
                }
                res = requests.get(
                    "https://api.modrinth.com/v2/project/fabric-api/version",
                    params=params,
                    headers=headers,
                    timeout=15
                )
                if res.status_code == 200:
                    versions = res.json()
            except Exception as e:
                print(f"Error querying any Fabric API versions: {e}")

        if not versions:
            status_cb("Warning: No Fabric API version found on Modrinth. Skipping auto-download.")
            return True, "No Fabric API version found on Modrinth."

        files = versions[0].get("files", [])
        selected_file = next((f for f in files if f.get("primary")), files[0] if files else None)
        if not selected_file:
            status_cb("Warning: No downloadable Fabric API file found. Skipping auto-download.")
            return True, "No downloadable Fabric API file found."

        try:
            os.makedirs(mods_dir, exist_ok=True)
            dest_path = os.path.join(mods_dir, selected_file["filename"])
            download = requests.get(selected_file["url"], headers=headers, timeout=60)
            if download.status_code != 200:
                status_cb(f"Warning: Could not download Fabric API (HTTP {download.status_code}). Skipping auto-download.")
                return True, f"Could not download Fabric API: HTTP {download.status_code}"

            with open(dest_path, "wb") as f:
                f.write(download.content)

            return True, selected_file["filename"]
        except Exception as e:
            status_cb(f"Warning: Error downloading Fabric API ({e}). Skipping auto-download.")
            return True, str(e)

    def create_server(self, server_type, version, target_dir, progress_cb, status_cb, gamemode="Survival", setup_bedrock=False):
        import requests
        os.makedirs(target_dir, exist_ok=True)
        
        status_cb(f"Resolving download for {server_type} {version}...")
        progress_cb(0)
        
        # 1. Resolve URL
        download_url = None
        jar_name = f"{server_type.lower()}.jar"
        
        try:
            if server_type == "Vanilla":
                res = requests.get("https://launchermeta.mojang.com/mc/game/version_manifest_v2.json", timeout=10).json()
                version_url = None
                for v in res["versions"]:
                    if v["id"] == version:
                        version_url = v["url"]
                        break
                if not version_url:
                    return False, f"Could not find version {version} in Mojang manifest."
                
                v_res = requests.get(version_url, timeout=10).json()
                download_url = v_res["downloads"]["server"]["url"]
                jar_name = "server.jar"
                
            elif server_type == "Paper":
                api_url = f"https://api.papermc.io/v2/projects/paper/versions/{version}"
                res = requests.get(api_url, timeout=10).json()
                if "builds" not in res:
                    return False, f"Could not find Paper version {version}."
                latest_build = res["builds"][-1]
                download_url = f"https://api.papermc.io/v2/projects/paper/versions/{version}/builds/{latest_build}/downloads/paper-{version}-{latest_build}.jar"
                jar_name = "paper.jar"
                
            elif server_type == "Purpur":
                download_url = f"https://api.purpurmc.org/v2/purpur/{version}/latest/download"
                jar_name = "purpur.jar"
                
            elif server_type == "Spigot":
                download_url = f"https://download.getbukkit.org/spigot/spigot-{version}.jar"
                jar_name = "spigot.jar"
                
            elif server_type == "Fabric":
                # Get latest Fabric loader version
                loader_res = requests.get("https://meta.fabricmc.net/v2/versions/loader", timeout=10).json()
                if not loader_res:
                    return False, "Could not fetch Fabric loader versions."
                latest_loader = loader_res[0]["version"]
                
                # Fetch installer list to get installer version
                installer_res = requests.get("https://meta.fabricmc.net/v2/versions/installer", timeout=10).json()
                if not installer_res:
                    return False, "Could not fetch Fabric installer versions."
                latest_installer = installer_res[0]["version"]
                
                download_url = f"https://meta.fabricmc.net/v2/versions/loader/{version}/{latest_loader}/{latest_installer}/server/jar"
                jar_name = "fabric-server.jar"
                
            elif server_type in ["Forge", "NeoForge"]:
                if server_type == "Forge":
                    promo_res = requests.get("https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json", timeout=10).json()
                    promos = promo_res.get("promos", {})
                    
                    forge_version = promos.get(f"{version}-recommended") or promos.get(f"{version}-latest")
                    if not forge_version:
                        return False, f"Could not automatically find Forge version for {version}."
                        
                    download_url = f"https://maven.minecraftforge.net/net/minecraftforge/forge/{version}-{forge_version}/forge-{version}-{forge_version}-installer.jar"
                    jar_name = "forge-installer.jar"
                else:
                    # NeoForge
                    parts = version.split('.')
                    if len(parts) >= 2 and parts[0] == "1":
                        major = parts[1]
                        meta_url = "https://maven.neoforged.net/releases/net/neoforged/neoforge/maven-metadata.xml"
                        import xml.etree.ElementTree as ET
                        meta_res = requests.get(meta_url, timeout=10)
                        root = ET.fromstring(meta_res.content)
                        versions_list = [v.text for v in root.findall(".//version")]
                        
                        matching = [v for v in versions_list if v.startswith(f"{major}.")]
                        if not matching:
                            return False, f"Could not find NeoForge version for MC {version}."
                        neoforge_version = matching[-1]
                        
                        download_url = f"https://maven.neoforged.net/releases/net/neoforged/neoforge/{neoforge_version}/neoforge-{neoforge_version}-installer.jar"
                        jar_name = "neoforge-installer.jar"
                    else:
                        return False, f"NeoForge is not supported on legacy Minecraft version {version}."
            
            else:
                return False, f"Unsupported server type {server_type}."
                
        except Exception as e:
            return False, f"Failed to resolve version URL: {e}"

        # 2. Download the Jar
        status_cb(f"Downloading {jar_name}...")
        dest_path = os.path.join(target_dir, jar_name)
        
        try:
            r = requests.get(download_url, stream=True, timeout=30)
            if r.status_code != 200:
                return False, f"Server returned error code {r.status_code} during download."
                
            total_size = int(r.headers.get('content-length', 0))
            downloaded = 0
            
            with open(dest_path, 'wb') as f:
                for chunk in r.iter_content(chunk_size=8192):
                    if chunk:
                        f.write(chunk)
                        downloaded += len(chunk)
                        if total_size > 0:
                            progress_cb(downloaded / total_size)
                            
        except Exception as e:
            if os.path.exists(dest_path):
                os.remove(dest_path)
            return False, f"Download failed: {e}"

        # 3. Post-install for Forge/NeoForge (Run installer)
        if server_type in ["Forge", "NeoForge"]:
            status_cb(f"Running {server_type} installer (this can take 1-2 minutes)...")
            progress_cb(0.5)
            
            java_path = self.config_manager.get("java_path") or "java"
            cmd = [java_path, "-jar", jar_name, "--installServer"]
            try:
                startupinfo = subprocess.STARTUPINFO()
                startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
                startupinfo.wShowWindow = 0
                
                proc = subprocess.Popen(
                    cmd,
                    cwd=target_dir,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                    startupinfo=startupinfo
                )
                proc.wait()
                
                if os.path.exists(dest_path):
                    os.remove(dest_path)
                
                files = os.listdir(target_dir)
                has_jars = any(f.endswith(".jar") for f in files)
                has_run_sh = any("run." in f for f in files)
                if not has_jars and not has_run_sh:
                    return False, "Installer completed, but no server files were created."
                    
            except Exception as e:
                return False, f"Failed to run installer: {e}"

        # 4. Generate eula.txt and server.properties
        status_cb("Generating configuration files...")
        progress_cb(0.9)
        
        eula_path = os.path.join(target_dir, "eula.txt")
        if not os.path.exists(eula_path):
            try:
                with open(eula_path, "w") as f:
                    f.write("eula=true\n")
            except Exception:
                pass
                
        properties_path = os.path.join(target_dir, "server.properties")
        gm = "survival"
        hc = "false"
        if gamemode == "Creative":
            gm = "creative"
        elif gamemode == "Hardcore":
            gm = "survival"
            hc = "true"
            
        updates = {
            "gamemode": gm,
            "hardcore": hc,
            "force-gamemode": "true",
            "online-mode": "false",
            "server-port": "25565",
            "motd": f"Alien {server_type} Server"
        }
        self.update_server_properties(properties_path, updates)

        # 5. Optional Bedrock setup (Geyser + Floodgate)
        if setup_bedrock:
            if server_type in ["Paper", "Purpur", "Spigot"]:
                status_cb("Downloading Geyser & Floodgate plugins for Bedrock compatibility...")
                plugins_dir = os.path.join(target_dir, "plugins")
                os.makedirs(plugins_dir, exist_ok=True)
                
                geyser_url = "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot"
                floodgate_url = "https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot"
                
                geyser_dest = os.path.join(plugins_dir, "Geyser-Spigot.jar")
                floodgate_dest = os.path.join(plugins_dir, "Floodgate-Spigot.jar")
            elif server_type == "Fabric":
                status_cb("Downloading Geyser & Floodgate Fabric mods for Bedrock compatibility...")
                mods_dir = os.path.join(target_dir, "mods")
                os.makedirs(mods_dir, exist_ok=True)

                api_success, api_msg = self.download_fabric_api(version, mods_dir, status_cb)
                if not api_success:
                    return False, api_msg
                
                geyser_url = "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/fabric"
                
                # Fetch Floodgate-Fabric from Modrinth API
                floodgate_url = None
                try:
                    status_cb("Resolving Floodgate Fabric mod from Modrinth...")
                    mr = requests.get("https://api.modrinth.com/v2/project/floodgate/version", timeout=10)
                    if mr.status_code == 200:
                        versions = mr.json()
                        # 1. Try exact version match
                        fabric_versions = [
                            v for v in versions 
                            if "fabric" in v.get("loaders", []) and version in v.get("game_versions", [])
                        ]
                        # 2. Try major version match (e.g. if version is 26.1.2, try 26.1)
                        if not fabric_versions and "." in version:
                            major_version = ".".join(version.split(".")[:2])
                            fabric_versions = [
                                v for v in versions 
                                if "fabric" in v.get("loaders", []) and major_version in v.get("game_versions", [])
                            ]
                        # 3. Fallback to any fabric loader version
                        if not fabric_versions:
                            fabric_versions = [v for v in versions if "fabric" in v.get("loaders", [])]
                            
                        if fabric_versions and fabric_versions[0].get("files"):
                            floodgate_url = fabric_versions[0]["files"][0]["url"]
                except Exception as e:
                    print(f"Error resolving Floodgate from Modrinth: {e}")
                
                # Fallback URL if Modrinth API fails or is slow
                if not floodgate_url:
                    if version.startswith("26.1"):
                        floodgate_url = "https://cdn.modrinth.com/data/bWrNNfkb/versions/fD4J9lnX/Floodgate-Fabric-2.2.6-b63.jar"
                    else:
                        floodgate_url = "https://cdn.modrinth.com/data/bWrNNfkb/versions/urOFTrVX/Floodgate-Fabric-2.2.6-b67.jar"
                
                geyser_dest = os.path.join(mods_dir, "Geyser-Fabric.jar")
                floodgate_dest = os.path.join(mods_dir, "Floodgate-Fabric.jar")
            else:
                geyser_url = None
                status_cb(f"Note: Bedrock compatibility is not supported on {server_type}.")

            if geyser_url:
                # Download Geyser
                try:
                    status_cb(f"Downloading Geyser for {server_type}...")
                    gr = requests.get(geyser_url, timeout=30)
                    if gr.status_code == 200:
                        with open(geyser_dest, "wb") as gf:
                            gf.write(gr.content)
                    else:
                        print(f"Failed downloading Geyser: {gr.status_code}")
                except Exception as e:
                    print(f"Error downloading Geyser: {e}")
                    
                # Download Floodgate
                try:
                    status_cb(f"Downloading Floodgate for {server_type}...")
                    fr = requests.get(floodgate_url, timeout=30)
                    if fr.status_code == 200:
                        with open(floodgate_dest, "wb") as ff:
                            ff.write(fr.content)
                    else:
                        print(f"Failed downloading Floodgate: {fr.status_code}")
                except Exception as e:
                    print(f"Error downloading Floodgate: {e}")

        status_cb(f"Successfully created {server_type} server!")
        progress_cb(1.0)
        return True, target_dir
